<?php return array(
    'root' => array(
        'name' => '__root__',
        'pretty_version' => 'dev-main',
        'version' => 'dev-main',
        'reference' => 'f309e0655b2eb67de791ef719560b49fb55de3ac',
        'type' => 'project',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        '__root__' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'reference' => 'f309e0655b2eb67de791ef719560b49fb55de3ac',
            'type' => 'project',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/collections' => array(
            'pretty_version' => '2.4.0',
            'version' => '2.4.0.0',
            'reference' => '9acfeea2e8666536edff3d77c531261c63680160',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/collections',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/dbal' => array(
            'pretty_version' => '3.10.3',
            'version' => '3.10.3.0',
            'reference' => '65edaca19a752730f290ec2fb89d593cb40afb43',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/dbal',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/deprecations' => array(
            'pretty_version' => '1.1.5',
            'version' => '1.1.5.0',
            'reference' => '459c2f5dd3d6a4633d3b5f46ee2b1c40f57d3f38',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/deprecations',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/doctrine-bundle' => array(
            'pretty_version' => '2.18.1',
            'version' => '2.18.1.0',
            'reference' => 'b769877014de053da0e5cbbb63d0ea2f3b2fea76',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../doctrine/doctrine-bundle',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/doctrine-migrations-bundle' => array(
            'pretty_version' => '3.7.0',
            'version' => '3.7.0.0',
            'reference' => '1e380c6dd8ac8488217f39cff6b77e367f1a644b',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../doctrine/doctrine-migrations-bundle',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/event-manager' => array(
            'pretty_version' => '2.0.1',
            'version' => '2.0.1.0',
            'reference' => 'b680156fa328f1dfd874fd48c7026c41570b9c6e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/event-manager',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/inflector' => array(
            'pretty_version' => '2.1.0',
            'version' => '2.1.0.0',
            'reference' => '6d6c96277ea252fc1304627204c3d5e6e15faa3b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/inflector',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/instantiator' => array(
            'pretty_version' => '2.0.0',
            'version' => '2.0.0.0',
            'reference' => 'c6222283fa3f4ac679f8b9ced9a4e23f163e80d0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/instantiator',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/lexer' => array(
            'pretty_version' => '3.0.1',
            'version' => '3.0.1.0',
            'reference' => '31ad66abc0fc9e1a1f2d9bc6a42668d2fbbcd6dd',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/lexer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/migrations' => array(
            'pretty_version' => '3.9.5',
            'version' => '3.9.5.0',
            'reference' => '1b823afbc40f932dae8272574faee53f2755eac5',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/migrations',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/orm' => array(
            'pretty_version' => '3.5.7',
            'version' => '3.5.7.0',
            'reference' => 'f18de9d569f00ed6eb9dac4b33c7844d705d17da',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/orm',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/persistence' => array(
            'pretty_version' => '4.1.1',
            'version' => '4.1.1.0',
            'reference' => 'b9c49ad3558bb77ef973f4e173f2e9c2eca9be09',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/persistence',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/sql-formatter' => array(
            'pretty_version' => '1.5.3',
            'version' => '1.5.3.0',
            'reference' => 'a8af23a8e9d622505baa2997465782cbe8bb7fc7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/sql-formatter',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'gedmo/doctrine-extensions' => array(
            'pretty_version' => 'v3.21.0',
            'version' => '3.21.0.0',
            'reference' => 'eb53dfcb2b592327b76ac5226fbb003d32aea37e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../gedmo/doctrine-extensions',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'masterminds/html5' => array(
            'pretty_version' => '2.10.0',
            'version' => '2.10.0.0',
            'reference' => 'fcf91eb64359852f00d921887b219479b4f21251',
            'type' => 'library',
            'install_path' => __DIR__ . '/../masterminds/html5',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'myclabs/deep-copy' => array(
            'pretty_version' => '1.13.4',
            'version' => '1.13.4.0',
            'reference' => '07d290f0c47959fd5eed98c95ee5602db07e0b6a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../myclabs/deep-copy',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'nikic/php-parser' => array(
            'pretty_version' => 'v5.6.2',
            'version' => '5.6.2.0',
            'reference' => '3a454ca033b9e06b63282ce19562e892747449bb',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nikic/php-parser',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phar-io/manifest' => array(
            'pretty_version' => '2.0.4',
            'version' => '2.0.4.0',
            'reference' => '54750ef60c58e43759730615a392c31c80e23176',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phar-io/manifest',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phar-io/version' => array(
            'pretty_version' => '3.2.1',
            'version' => '3.2.1.0',
            'reference' => '4f7fd7836c6f332bb2933569e566a0d6c4cbed74',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phar-io/version',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/php-code-coverage' => array(
            'pretty_version' => '12.4.0',
            'version' => '12.4.0.0',
            'reference' => '67e8aed88f93d0e6e1cb7effe1a2dfc2fee6022c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-code-coverage',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/php-file-iterator' => array(
            'pretty_version' => '6.0.0',
            'version' => '6.0.0.0',
            'reference' => '961bc913d42fe24a257bfff826a5068079ac7782',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-file-iterator',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/php-invoker' => array(
            'pretty_version' => '6.0.0',
            'version' => '6.0.0.0',
            'reference' => '12b54e689b07a25a9b41e57736dfab6ec9ae5406',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-invoker',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/php-text-template' => array(
            'pretty_version' => '5.0.0',
            'version' => '5.0.0.0',
            'reference' => 'e1367a453f0eda562eedb4f659e13aa900d66c53',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-text-template',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/php-timer' => array(
            'pretty_version' => '8.0.0',
            'version' => '8.0.0.0',
            'reference' => 'f258ce36aa457f3aa3339f9ed4c81fc66dc8c2cc',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-timer',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/phpunit' => array(
            'pretty_version' => '12.4.4',
            'version' => '12.4.4.0',
            'reference' => '9253ec75a672e39fcc9d85bdb61448215b8162c7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/phpunit',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'psr/cache' => array(
            'pretty_version' => '3.0.0',
            'version' => '3.0.0.0',
            'reference' => 'aa5030cfa5405eccfdcb1083ce040c2cb8d253bf',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/cache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/cache-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '2.0|3.0',
            ),
        ),
        'psr/clock' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'reference' => 'e41a24703d4560fd0acb709162f73b8adfc3aa0d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/clock',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/container' => array(
            'pretty_version' => '2.0.2',
            'version' => '2.0.2.0',
            'reference' => 'c71ecc56dfe541dbd90c5360474fbc405f8d5963',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/container',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/container-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.1|2.0',
            ),
        ),
        'psr/event-dispatcher' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'reference' => 'dbefd12671e8a14ec7f180cab83036ed26714bb0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/event-dispatcher',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/event-dispatcher-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/log' => array(
            'pretty_version' => '3.0.2',
            'version' => '3.0.2.0',
            'reference' => 'f16e1d5863e37f8d8c2a01719f5b34baa2b714d3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/log',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/log-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0|2.0|3.0',
            ),
        ),
        'psr/simple-cache-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0|2.0|3.0',
            ),
        ),
        'sebastian/cli-parser' => array(
            'pretty_version' => '4.2.0',
            'version' => '4.2.0.0',
            'reference' => '90f41072d220e5c40df6e8635f5dafba2d9d4d04',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/cli-parser',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/comparator' => array(
            'pretty_version' => '7.1.3',
            'version' => '7.1.3.0',
            'reference' => 'dc904b4bb3ab070865fa4068cd84f3da8b945148',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/comparator',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/complexity' => array(
            'pretty_version' => '5.0.0',
            'version' => '5.0.0.0',
            'reference' => 'bad4316aba5303d0221f43f8cee37eb58d384bbb',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/complexity',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/diff' => array(
            'pretty_version' => '7.0.0',
            'version' => '7.0.0.0',
            'reference' => '7ab1ea946c012266ca32390913653d844ecd085f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/diff',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/environment' => array(
            'pretty_version' => '8.0.3',
            'version' => '8.0.3.0',
            'reference' => '24a711b5c916efc6d6e62aa65aa2ec98fef77f68',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/environment',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/exporter' => array(
            'pretty_version' => '7.0.2',
            'version' => '7.0.2.0',
            'reference' => '016951ae10980765e4e7aee491eb288c64e505b7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/exporter',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/global-state' => array(
            'pretty_version' => '8.0.2',
            'version' => '8.0.2.0',
            'reference' => 'ef1377171613d09edd25b7816f05be8313f9115d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/global-state',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/lines-of-code' => array(
            'pretty_version' => '4.0.0',
            'version' => '4.0.0.0',
            'reference' => '97ffee3bcfb5805568d6af7f0f893678fc076d2f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/lines-of-code',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/object-enumerator' => array(
            'pretty_version' => '7.0.0',
            'version' => '7.0.0.0',
            'reference' => '1effe8e9b8e068e9ae228e542d5d11b5d16db894',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/object-enumerator',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/object-reflector' => array(
            'pretty_version' => '5.0.0',
            'version' => '5.0.0.0',
            'reference' => '4bfa827c969c98be1e527abd576533293c634f6a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/object-reflector',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/recursion-context' => array(
            'pretty_version' => '7.0.1',
            'version' => '7.0.1.0',
            'reference' => '0b01998a7d5b1f122911a66bebcb8d46f0c82d8c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/recursion-context',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/type' => array(
            'pretty_version' => '6.0.3',
            'version' => '6.0.3.0',
            'reference' => 'e549163b9760b8f71f191651d22acf32d56d6d4d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/type',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/version' => array(
            'pretty_version' => '6.0.0',
            'version' => '6.0.0.0',
            'reference' => '3e6ccf7657d4f0a59200564b08cead899313b53c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/version',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'staabm/side-effects-detector' => array(
            'pretty_version' => '1.0.5',
            'version' => '1.0.5.0',
            'reference' => 'd8334211a140ce329c13726d4a715adbddd0a163',
            'type' => 'library',
            'install_path' => __DIR__ . '/../staabm/side-effects-detector',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'stof/doctrine-extensions-bundle' => array(
            'pretty_version' => 'v1.14.0',
            'version' => '1.14.0.0',
            'reference' => 'bdf3eb10baeb497ac5985b8f78a6cf55862c2662',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../stof/doctrine-extensions-bundle',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/asset' => array(
            'pretty_version' => 'v7.3.0',
            'version' => '7.3.0.0',
            'reference' => '56c4d9f759247c4e07d8549e3baf7493cb9c3e4b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/asset',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/browser-kit' => array(
            'pretty_version' => 'v7.3.6',
            'version' => '7.3.6.0',
            'reference' => 'e9a9fd604296b17bf90939c3647069f1f16ef04e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/browser-kit',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'symfony/cache' => array(
            'pretty_version' => 'v7.3.6',
            'version' => '7.3.6.0',
            'reference' => '1277a1ec61c8d93ea61b2a59738f1deb9bfb6701',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/cache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/cache-contracts' => array(
            'pretty_version' => 'v3.6.0',
            'version' => '3.6.0.0',
            'reference' => '5d68a57d66910405e5c0b63d6f0af941e66fc868',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/cache-contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/cache-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.1|2.0|3.0',
            ),
        ),
        'symfony/config' => array(
            'pretty_version' => 'v7.3.6',
            'version' => '7.3.6.0',
            'reference' => '9d18eba95655a3152ae4c1d53c6cc34eb4d4a0b7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/config',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/console' => array(
            'pretty_version' => 'v7.3.6',
            'version' => '7.3.6.0',
            'reference' => 'c28ad91448f86c5f6d9d2c70f0cf68bf135f252a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/console',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/css-selector' => array(
            'pretty_version' => 'v7.3.6',
            'version' => '7.3.6.0',
            'reference' => '84321188c4754e64273b46b406081ad9b18e8614',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/css-selector',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'symfony/dependency-injection' => array(
            'pretty_version' => 'v7.3.6',
            'version' => '7.3.6.0',
            'reference' => '98af8bb46c56aedd9dd5a7f0414fc72bf2dcfe69',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/dependency-injection',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/deprecation-contracts' => array(
            'pretty_version' => 'v3.6.0',
            'version' => '3.6.0.0',
            'reference' => '63afe740e99a13ba87ec199bb07bbdee937a5b62',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/deprecation-contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/doctrine-bridge' => array(
            'pretty_version' => 'v7.3.5',
            'version' => '7.3.5.0',
            'reference' => 'e7d308bd44ff8673a259e2727d13af6a93a5d83e',
            'type' => 'symfony-bridge',
            'install_path' => __DIR__ . '/../symfony/doctrine-bridge',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/dom-crawler' => array(
            'pretty_version' => 'v7.3.3',
            'version' => '7.3.3.0',
            'reference' => 'efa076ea0eeff504383ff0dcf827ea5ce15690ba',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/dom-crawler',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'symfony/dotenv' => array(
            'pretty_version' => 'v7.3.2',
            'version' => '7.3.2.0',
            'reference' => '2192790a11f9e22cbcf9dc705a3ff22a5503923a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/dotenv',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/error-handler' => array(
            'pretty_version' => 'v7.3.6',
            'version' => '7.3.6.0',
            'reference' => 'bbe40bfab84323d99dab491b716ff142410a92a8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/error-handler',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/event-dispatcher' => array(
            'pretty_version' => 'v7.3.3',
            'version' => '7.3.3.0',
            'reference' => 'b7dc69e71de420ac04bc9ab830cf3ffebba48191',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/event-dispatcher',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/event-dispatcher-contracts' => array(
            'pretty_version' => 'v3.6.0',
            'version' => '3.6.0.0',
            'reference' => '59eb412e93815df44f05f342958efa9f46b1e586',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/event-dispatcher-contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/event-dispatcher-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '2.0|3.0',
            ),
        ),
        'symfony/filesystem' => array(
            'pretty_version' => 'v7.3.6',
            'version' => '7.3.6.0',
            'reference' => 'e9bcfd7837928ab656276fe00464092cc9e1826a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/filesystem',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/finder' => array(
            'pretty_version' => 'v7.3.5',
            'version' => '7.3.5.0',
            'reference' => '9f696d2f1e340484b4683f7853b273abff94421f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/finder',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/flex' => array(
            'pretty_version' => 'v2.10.0',
            'version' => '2.10.0.0',
            'reference' => '9cd384775973eabbf6e8b05784dda279fc67c28d',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/../symfony/flex',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/framework-bundle' => array(
            'pretty_version' => 'v7.3.6',
            'version' => '7.3.6.0',
            'reference' => 'cabfdfa82bc4f75d693a329fe263d96937636b77',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../symfony/framework-bundle',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/http-foundation' => array(
            'pretty_version' => 'v7.3.7',
            'version' => '7.3.7.0',
            'reference' => 'db488a62f98f7a81d5746f05eea63a74e55bb7c4',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/http-foundation',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/http-kernel' => array(
            'pretty_version' => 'v7.3.7',
            'version' => '7.3.7.0',
            'reference' => '10b8e9b748ea95fa4539c208e2487c435d3c87ce',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/http-kernel',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/maker-bundle' => array(
            'pretty_version' => 'v1.65.0',
            'version' => '1.65.0.0',
            'reference' => '9a0276d7486b29cae641b4a0a85d5e5cc149bff2',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../symfony/maker-bundle',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'symfony/polyfill-ctype' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'symfony/polyfill-iconv' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'symfony/polyfill-intl-grapheme' => array(
            'pretty_version' => 'v1.33.0',
            'version' => '1.33.0.0',
            'reference' => '380872130d3a5dd3ace2f4010d95125fde5d5c70',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-grapheme',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-intl-normalizer' => array(
            'pretty_version' => 'v1.33.0',
            'version' => '1.33.0.0',
            'reference' => '3833d7255cc303546435cb650316bff708a1c75c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-normalizer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-mbstring' => array(
            'pretty_version' => 'v1.33.0',
            'version' => '1.33.0.0',
            'reference' => '6d857f4d76bd4b343eac26d6b539585d2bc56493',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-mbstring',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php72' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'symfony/polyfill-php73' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'symfony/polyfill-php74' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'symfony/polyfill-php80' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'symfony/polyfill-php81' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'symfony/polyfill-php82' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'symfony/polyfill-php83' => array(
            'pretty_version' => 'v1.33.0',
            'version' => '1.33.0.0',
            'reference' => '17f6f9a6b1735c0f163024d959f700cfbc5155e5',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php83',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php84' => array(
            'pretty_version' => 'v1.33.0',
            'version' => '1.33.0.0',
            'reference' => 'd8ced4d875142b6a7426000426b8abc631d6b191',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php84',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/process' => array(
            'pretty_version' => 'v7.3.4',
            'version' => '7.3.4.0',
            'reference' => 'f24f8f316367b30810810d4eb30c543d7003ff3b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/process',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'symfony/routing' => array(
            'pretty_version' => 'v7.3.6',
            'version' => '7.3.6.0',
            'reference' => 'c97abe725f2a1a858deca629a6488c8fc20c3091',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/routing',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/runtime' => array(
            'pretty_version' => 'v7.3.4',
            'version' => '7.3.4.0',
            'reference' => '3550e2711e30bfa5d808514781cd52d1cc1d9e9f',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/../symfony/runtime',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/service-contracts' => array(
            'pretty_version' => 'v3.6.1',
            'version' => '3.6.1.0',
            'reference' => '45112560a3ba2d715666a509a0bc9521d10b6c43',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/service-contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/service-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.1|2.0|3.0',
            ),
        ),
        'symfony/stopwatch' => array(
            'pretty_version' => 'v7.3.0',
            'version' => '7.3.0.0',
            'reference' => '5a49289e2b308214c8b9c2fda4ea454d8b8ad7cd',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/stopwatch',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/string' => array(
            'pretty_version' => 'v7.3.4',
            'version' => '7.3.4.0',
            'reference' => 'f96476035142921000338bad71e5247fbc138872',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/string',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/translation' => array(
            'pretty_version' => 'v7.3.4',
            'version' => '7.3.4.0',
            'reference' => 'ec25870502d0c7072d086e8ffba1420c85965174',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/translation',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/translation-contracts' => array(
            'pretty_version' => 'v3.6.1',
            'version' => '3.6.1.0',
            'reference' => '65a8bc82080447fae78373aa10f8d13b38338977',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/translation-contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/translation-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '2.3|3.0',
            ),
        ),
        'symfony/twig-bridge' => array(
            'pretty_version' => 'v7.3.6',
            'version' => '7.3.6.0',
            'reference' => 'd1aaec8eee1f5591f56b9efe00194d73a8e38319',
            'type' => 'symfony-bridge',
            'install_path' => __DIR__ . '/../symfony/twig-bridge',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'symfony/twig-bundle' => array(
            'pretty_version' => 'v7.3.4',
            'version' => '7.3.4.0',
            'reference' => 'da5c778a8416fcce5318737c4d944f6fa2bb3f81',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../symfony/twig-bundle',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'symfony/validator' => array(
            'pretty_version' => 'v7.3.7',
            'version' => '7.3.7.0',
            'reference' => '8290a095497c3fe5046db21888d1f75b54ddf39d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/validator',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/var-dumper' => array(
            'pretty_version' => 'v7.3.5',
            'version' => '7.3.5.0',
            'reference' => '476c4ae17f43a9a36650c69879dcf5b1e6ae724d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/var-dumper',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/var-exporter' => array(
            'pretty_version' => 'v7.3.4',
            'version' => '7.3.4.0',
            'reference' => '0f020b544a30a7fe8ba972e53ee48a74c0bc87f4',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/var-exporter',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/web-profiler-bundle' => array(
            'pretty_version' => 'v7.3.5',
            'version' => '7.3.5.0',
            'reference' => 'c2ed11cc0e9093fe0425ad52498d26a458842e0c',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../symfony/web-profiler-bundle',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'symfony/webpack-encore-bundle' => array(
            'pretty_version' => 'v2.3.0',
            'version' => '2.3.0.0',
            'reference' => '7ae70d44c24c3b913f308af8396169b5c6d9e0f5',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../symfony/webpack-encore-bundle',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/yaml' => array(
            'pretty_version' => 'v7.3.5',
            'version' => '7.3.5.0',
            'reference' => '90208e2fc6f68f613eae7ca25a2458a931b1bacc',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/yaml',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'theseer/tokenizer' => array(
            'pretty_version' => '1.3.1',
            'version' => '1.3.1.0',
            'reference' => 'b7489ce515e168639d17feec34b8847c326b0b3c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../theseer/tokenizer',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'twig/twig' => array(
            'pretty_version' => 'v3.22.0',
            'version' => '3.22.0.0',
            'reference' => '4509984193026de413baf4ba80f68590a7f2c51d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../twig/twig',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
    ),
);
